version: '3.4'

services:
  pji340_pg:
    image: postgres
    container_name: pji340_pg
    restart: always
    ports:
      - 5432:5432
    environment:
      TZ: utc
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: test
      POSTGRES_DB: pji340
    volumes:
      - pgdata:/data/postgres
  # pji340_backend:
  #   build: .
  #   container_name: pji340_backend
  #   volumes:
  #     - .:/usr/app
  #   environment:
  #     TZ: utc
  #     NODE_ENV: production
  #   ports:
  #     - 3333:3333
  #   links:
  #     - pg_pji340
  #   depends_on:
  #     - pg_pji340
volumes:
  pgdata:
    driver: local
