version: '3.4'

services:
  # pg_pji240:
  #   image: postgres
  #   container_name: pg_pji240
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     TZ: utc
  #     POSTGRES_USER: docker
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: pji240
  #   volumes:
  #     - pgdata:/data/postgres
  app_pji240:
    build: .
    container_name: app_pji240
    volumes:
      - .:/usr/app
    environment:
      TZ: utc
      NODE_ENV: production
    ports:
      - 3333:3333
    # links:
    #   - pg_pji240
    # depends_on:
    #   - pg_pji240
# volumes:
  # pgdata:
  #   driver: local
